#!/usr/bin/python

if __name__ == '__main__':
    import os
    import pandas as pd
    import tushare as ts
    from tushare_easy.getdata import RunFunc, GetData
    get_code = RunFunc()
    get_code.set_func(ts.get_stock_basics)
    codes = get_code.run().index.values
    home = os.path.join(os.environ['HOME'], 'data', 'ts', 'k_chart')
    getdf = GetData(codes, home=home)
    getdf.run_loop()
